#!/bin/bash
# Assumes that the environment variable UNISON_DIR is set to the top of the
# Unison repo
# MULTIBACKEND_DIR=$UNISON_DIR/src/solvers/multi_backend
export PATH=$UNISON_DIR/src/solvers/multi_backend:$PATH
MULTIBACKEND_DIR=$UNISON_DIR/src/secportfolio/build/
$MULTIBACKEND_DIR/secportfolio "$@" +RTS -N2
